### ISSUE TITLE
Protocol integration test

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/openst-protocol#14]
End-to-end integration test scripts for deployment and integrated protocol steps.

- [x] truffle complete deployment process
- [x] Initialize Transfer to ST' Contract Address - @abhayks1 
- [x] stake ST for ST' - @ben
- [x] propose and register Branded Token - @kushal-ladha 
- [x] stake ST for BT - @abhayks1 
- [x] transact with BT - @ben
- [x] unstake BT from different user - @kushal-ladha 
- [x] unstake ST' from different user - @abhayks1 
--- stretch goals ---
- protocol version upgrade - @ben

**Comment by abhayks1** [comment]
Initialize Transfer to ST' Contract Address - #22 
stake ST for BT - #23
