### ISSUE TITLE
Fix typo in Gate::processStaking, change stakerAddress to stakeAddress

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-protocol#170]
There is a typo in the variable name at line number 243 in `processStaking` of Gate contract

`processStaking` of `OpenSTValue` contract returns `stakeAddress`, i.e SimpleStake contract address.

the returned value from openSTValue.processStaking is assigned to variable named `stakerAddress`. In comment its mentioned correctly as stake address. So the intent of this ticket is to rectify the typo mistake of the variable to stakeAddress instead of stakerAddress.

In simple words `stakerAddress` changes to `stakeAddress`

_MOSA-124_

**Comment by jasonklein** [comment]
Resolved by #171.
