### ISSUE TITLE
[GATE] In rejectStakeRequest , msg.sender is worker not staker. Fix statement to delete stake request of staker

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenSTFoundation/openst-protocol#176]
1. Write a failing truffle test case to reproduce the bug
2. Fix the bug

L166 should read `delete stakeRequests[_staker];

Refer below link
https://github.com/OpenSTFoundation/openst-protocol/blob/8a2651e67d821e1ebdb7ba98ba57612fa03aea5b/contracts/Gate.sol#L166

**Comment by jasonklein** [comment]
Resolved by #177.
