### ISSUE TITLE
Gate::revertStaking should not require caller to be whitelisted worker

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-protocol#178]
Currently, revertStaking() function of Gate.sol contract requires the caller to be whitelisted worker.This is not needed anymore and should be removed.

Test case should be introduced that check:

- Check that stake exists and is unlocked, otherwise fail.
- Check that staked amount is transferred back to staker.
- If it's a whitelisted worker, then bounty is sent from OpenSTValue contract to Workers contract.
- If it's non whitelisted worker, then bounty is sent from OpenSTValue to msg.sender.
- Stake request should be deleted afterwards from Gate contract.

_MOSA-127_

**Comment by deepesh-kn** [comment]
**Update:** The bounty will be always transferred to workers contract.

**Comment by jasonklein** [comment]
Resolved by #180 .
