### ISSUE TITLE
Update all references to Gate to be Gateway

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-protocol#181]
Gate has been re-imagined as a Gateway with the Protocol upgrades that are upcoming.

The business side rational as mentioned in Slack is "Gateway as Gate represents a closing to keep things out, while Gateway represents an opening, which better reflects what Gateway is all about"

Please update all references to "Gate" to say "Gateway" to keep consistent with our plans on build and business side.

**Comment by jasonklein** [comment]
Resolved by #182.
