### ISSUE TITLE
Resolve all the compiler warnings after upgrading to solidity 0.4.23 

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-protocol#188]
**Problem**
After upgrading solidity version to 0.4.23, the compiler complains and generates below warnings

1. OpenSTValue
Warning: This declaration shadows an existing declaration.
Line 241: Stake storage stake = stakes[_stakingIntentHash];
Line 165 : function stake(

2. UtilityTokenAbstractMock
Warning: Base constructor arguments given twice.ProtocolVersioned(msg.sender)

3. MockTokenWarning: Base constructor arguments given twice.Owned()

**SolutionFix** the compiler warning.

ref: MOSA-52

**Comment by jasonklein** [comment]
Resolved by #189.
