### ISSUE TITLE
Same time calculation (block height calculation) across chains.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-protocol#202]
- now can introduce a medium wait time with Core:latestBlockHeight of the opposing chain
- we have the utility chain running at 2s; and perhaps later at 3s

so at constructor of Core.sol, OpenSTValue.sol and OpenSTUtility.sol we must take a new parameter uint256 _blockTime which is set by the interaction layer when deploying the contracts; for OpenSTValue/Utility this is the blocktime of the current chain; for the Core.sol contract, this is the blocktime of the alternate chain.
we must remove the constants BLOCKS_TO_WAIT_SHORT and _LONG and replace them with public variables blocksToWaitShort, blocksToWaitMedium and blocksToWaitLong. The similarly named functions can be removed; in the Mock contracts for OpenSTValue and Utility the mock-constructor can overwrite the value of these variables after the parent constructor has correctly set them for testing purposes. (similarly named functions can be removed from Mocks then as well).

we must introduce new constants TIME_TO_WAIT_SHORT, TIME_TO_WAIT_MEDIUM, TIME_TO_WAIT_LONG all uint256, respectively expressed in seconds as 1 hour, 5 days and two weeks.

the constructors must then set blocksToWaitX = TIME_TO_WAIT_X / _blockTime

Ref: MOSA-65

**Comment by deepesh-kn** [comment]
Update:
- variable `TIME_TO_WAIT_SHORT`,  `TIME_TO_WAIT_LONG`,  `blockToWaitShort` and  `blockTOWaitLong` is implemented in OpensSTValue and OpenSTUtility.

- variable `TIME_TO_WAIT_MEDIUM` and `blockToWait` is implemented in Core.sol and is named as `TIME_TO_WAIT`  and `remoteChainBlocksToWait` respectively

**Comment by jasonklein** [comment]
Resolved by #153.
