### ISSUE TITLE
Update Hasher arguments/returns names

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/openst-protocol#28]
`Hasher.sol` uses old arguments/returns names (i.e., `escrowUnlockHeight`). It should be brought in line with changes to `OpenSTValue.sol` and `OpenSTUtility.sol`.

**Comment by benjaminbollen** [comment]
for 0.9.2 as Hasher is a pure library, we should consider moving out as a deployed (undestroyable) library.  This requires updates to utility chain deployments, so not for 0.9.1

**Comment by benjaminbollen** [comment]
completed in #94

**Comment by jasonklein** [comment]
Resolved by #126 (if not earlier 🤔 ).
