### ISSUE TITLE
Unit test 0.9.1 contracts

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/openst-protocol#3]
Contracts include the below (this list should be updated as there are changes to the composition of contracts):

**Common**

- [x] Core.sol
- [x] Hasher.sol
- [x] ProtocolVersioned.sol
- [x] Registrar.sol

**Value Chain**

- [x] OpenSTValue.sol
- [x] SimpleStake.sol

**Utility Chain**

- [x] BrandedToken.sol
- [x] EIP20Token.sol // protocol extensions
- [x] OpenSTUtility.sol
- [x] STPrime.sol
- [x] UtilityTokenAbstract.sol

**Comment by jasonklein** [comment]
Testing `STPrime` is partially completed. Must update test to reflect enabled payability.

**Comment by jasonklein** [comment]
Hasher is indirectly tested.

**Comment by benjaminbollen** [comment]
is this completed ?

**Comment by benjaminbollen** [comment]
now it is completed :)
