### ISSUE TITLE
Complete code documentation to align with Natspec

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/openst-protocol#34]
- [ ] align code documentation to Natspec
- [x] produce docs
- [x] publish docs

**Comment by benjaminbollen** [comment]
completed for v0.9.1 with https://github.com/OpenSTFoundation/openst-protocol/pull/78

new problem: following solc natspec requirements makes the existsing code comments unreadable; so we need an intermediary parser to resolve such that the in code documentation is useful, as well as the produced output

cc @jasonklein

**Comment by jasonklein** [comment]
Closing per #116.
