### ISSUE TITLE
Unit tests: reversion functions

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/openst-protocol#45]
Add unit tests for:

- [x] OpenSTValue.revertStaking
- [x] OpenSTValue.revertUnstaking
- [x] OpenSTUtility.revertMinting
- [x] OpenSTUtility.revertRedemption

**Comment by abhayks1** [comment]
#68

**Comment by kushal-ladha** [comment]
Revert Minting: #67

**Comment by deepesh-kn** [comment]
OpenSTValue.revertStaking: #69
