### ISSUE TITLE
Integration Tests: Reversion Functions

### ISSUE THREAD

**Issue by abhayks1** [OpenSTFoundation/openst-protocol#48]
Add integration tests for:

- [x] OpenSTValue.revertStaking
- [x] OpenSTUtility.revertMinting
- [x] OpenSTUtility.revertRedemption
- [x] OpenSTValue.revertUnstaking

**Comment by kushal-ladha** [comment]
#49 Revert Staking
#50 Revert Minting

**Comment by abhayks1** [comment]
#51 Revert Redemption
#52 Revert Unstaking
