### ISSUE TITLE
BrandedToken - pass UUID parameters

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/openst-protocol#91]
- [x] pass UUID parameters into UtilityTokenAbstract constructor, except `openSTUtility`
- [x] require that UUID matches hash of parameters (calculation uses `msg.sender` in the place of `openSTUtility`)
- [x] expose public view function for conversionRate

Estimate: 8hr

**Comment by benjaminbollen** [comment]
> openSTUtility/the protocol is already a constructor argument for UtilityTokenAbstract.
we can remove OST.U from the argument list and use `msg.sender`, tightening the constraint

additional remark for specification after discussion on this topic:
1. in `UtilityTokenAbstract` store the address of the original `OpenST.Utility` address as `genesisOpenSTUtility` together with the other constants that form the pre-image to the `uuid`, such that the invariant is explicitly preserved (nb: `UtilityTokenAbstract is ProtocolVersioned` and we don't want the mutability of the protocol address known in `ProtocolVersioned` to break the invariant of the `uuid`)

**Comment by jasonklein** [comment]
@benjaminbollen: to confirm, does:
> together with the other constants that form the pre-image
mean that there should also be `genesisChainIdUtility` and `genesisChainIdValue`?

Presumably yes, since there is no guarantee that that information will be consistent between protocols.

**Comment by benjaminbollen** [comment]
yes, all three parameters can be stored and prefixed with `genesis`.

**Comment by jasonklein** [comment]
Resolved by #97.
