### ISSUE TITLE
Implement Hashlock on stake/mint and redeem/unstake

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/openst-protocol#94]
- [x] update naming in `Hasher.sol` #28; deprioritising moving hasher out as a library
- [x] include `hashLock` in `StakingIntentHash
- [x] include `hashLock` in `RedemptionIntentHash`
- [x] implement lock in `process_` functions
- [x] update unit tests for stake/mint
- [x] update integration tests for stake/mint
- [x] a. update unit tests for redeem/unstake
- [x] b. update integration tests for redeem/unstake
- [x] c. expose `unlockSecret` in events to make it easy to carry over unlockSecrets
- [x] remove fallback processing code paths

later tasks
- [x] implement required OST bounty for staking or redemption (can be delayed)
- [ ] implement hashlock in openst-platform

**Comment by benjaminbollen** [comment]
handover for tasks a. b. and c.

**Comment by jasonklein** [comment]
Disregarding the item, "implement hashlock in openst-platform", as (a) something to address in 0.9.4 and (b) inapposite for this repository.

Considering this resolved by #123 and subsequent work.
